stages:
  - build
  - dockerize
  - deploy

build-react:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./dist

dockerize:
  stage: dockerize
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - ci-test
  dependencies:
    - build-react
