stages:
  - build
  - dockerize
  - deploy

build-react:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./dist

build-container:
  stage: dockerize
  image: